[fiveg_core]
core_node ansible_host=192.168.56.101

[fiveg_ran]
ran_node ansible_host=192.168.56.102

[all:vars]
ansible_user=vagrant
ansible_password=vagrant
ansible_become=yes
ansible_become_pass=vagrant
# This points to the 3.8 version already in your Ubuntu Focal VMs
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o PreferredAuthentications=password -o StrictHostKeyChecking=no'